behaviors:
  Paladin:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 81920
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 50
    checkpoint_interval: 1000000
    max_steps: 150000000
    checkpoint_interval: 1000000
    time_horizon: 1024
    summary_freq: 50000

